### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [PiperKev/edgar-rice-burroughs_tarzan-the-untamed#1]
# Semantics

- [x] `chapter-4`: Instead of `<dfn>` for `Tar` and `Mangani`, let’s use a custom language per [8.2.9.7](https://standardebooks.org/manual/1.7.3/8-typography#8.2.9.7). We usually use `<dfn>` in endnotes and glossaries, and this doesn’t seem like the most appropriate use case.
- [x] `chapter-8`: `Kagoda!` also seems like it should be using a custom language.
- [x] `chapter-13`: Let’s add `<i xml:lang="ms>` (Malay) to `pisangs`. Pisang is only in M-W unabridged so it isn’t a familiar English word, and I think it will look strange to have pisang be unitalicized while scimatines is, when both of them are probably going to be equally unrecognizable to most readers.
- [x] `chapter-6`: `<em>` on “Kamerad” should be changed to `<i xml:lang="de">`. It’s only in Merriam-Webster Unabridged so it’s not considered English.

# Typography

- [x] `chapter-24`: You have a miscurled quotation mark in `’Played a little joke`.

# Meta

- [x] Remove the trailing `/` in `https://archive.org/details/tarzanuntamed00burriala/` from the colophon, imprint, and `content.opf`.
- [x] There should be a space between `A.` and `C.` in `A.C. McClurg` in the long description.
- [x] The last sentence of the long description seems choppy. “And he unexpectedly finds himself becoming a protector and ally for them both” seems redundant with “eventually teams up with” too.

**Comment by PiperKev** [comment]
Addressed issues.
